### ISSUE TITLE
Limit the database that we run in imiq db vm

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/imiq-database#1]
Currently that should only be the iarc_staging and the imiq_production imiq_map_production

**Comment by asjacobs** [comment]
Shouldn't that be 'imiq_staging', not 'iarcod_staging'?

On Mon, May 11, 2015 at 2:55 PM, Will Fisher <notifications@github.com>
wrote:

> Currently that should only be the iarc_staging and the imiq_production
> imiq_map_production
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gina-alaska/imiq-database/issues/1>.
>



-- 
Amy Jacobs
International Arctic Research Center
University of Alaska Fairbanks
PO Box 757335
Fairbanks, AK 99775-7335
email: asjacobs@alaska.edu
phone: 907-474-2416

**Comment by teknofire** [comment]
Eventually yes, but currently the imiq site is looking at iarcod_staging.  Once we have confirmed that the imiq_production is good to go for the production map and api we will be able to get rid of it.
