### ISSUE TITLE
Update database version table

### ISSUE THREAD

**Issue by teknofire** [gina-alaska/imiq-database#36]

**Comment by grimm** [comment]
Talked to Ross about this and we were thinking of doing Symantec type versioning.  Currently there are two records in the imiqversion table, one from 2014 and the other from 2015.  Version 1.0 and 1.1 respectively.  We were thinking that adding another decimal to those records would be easy and that way we can have major, minor, and patch versions.

**Comment by rwspicer** [comment]
done
